//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLOB.AuditTrail.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuditTrailLogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditTrailLogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyLOB.AuditTrail.Data.Resources.AuditTrailLogResources", typeof(AuditTrailLogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail Logs.
        /// </summary>
        public static string EntityPlural {
            get {
                return ResourceManager.GetString("EntityPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail Log.
        /// </summary>
        public static string EntitySingular {
            get {
                return ResourceManager.GetString("EntitySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string PropertyId {
            get {
                return ResourceManager.GetString("PropertyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Date.
        /// </summary>
        public static string PropertyLogDate {
            get {
                return ResourceManager.GetString("PropertyLogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Domain.
        /// </summary>
        public static string PropertyLogDomain {
            get {
                return ResourceManager.GetString("PropertyLogDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Entity.
        /// </summary>
        public static string PropertyLogEntity {
            get {
                return ResourceManager.GetString("PropertyLogEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Entity After.
        /// </summary>
        public static string PropertyLogEntityAfter {
            get {
                return ResourceManager.GetString("PropertyLogEntityAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Entity Before.
        /// </summary>
        public static string PropertyLogEntityBefore {
            get {
                return ResourceManager.GetString("PropertyLogEntityBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Id.
        /// </summary>
        public static string PropertyLogId {
            get {
                return ResourceManager.GetString("PropertyLogId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Operation.
        /// </summary>
        public static string PropertyLogOperation {
            get {
                return ResourceManager.GetString("PropertyLogOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        public static string PropertyLogTime {
            get {
                return ResourceManager.GetString("PropertyLogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log User Name.
        /// </summary>
        public static string PropertyLogUserName {
            get {
                return ResourceManager.GetString("PropertyLogUserName", resourceCulture);
            }
        }
    }
}
