//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLOB.Identity.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyLOB.Identity.Data.Resources.UserResources", typeof(UserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string EntityPlural {
            get {
                return ResourceManager.GetString("EntityPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string EntitySingular {
            get {
                return ResourceManager.GetString("EntitySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Failed Count.
        /// </summary>
        public static string PropertyAccessFailedCount {
            get {
                return ResourceManager.GetString("PropertyAccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string PropertyEmail {
            get {
                return ResourceManager.GetString("PropertyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail Confirmed.
        /// </summary>
        public static string PropertyEmailConfirmed {
            get {
                return ResourceManager.GetString("PropertyEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string PropertyId {
            get {
                return ResourceManager.GetString("PropertyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Locked ?.
        /// </summary>
        public static string PropertyLockoutEnabled {
            get {
                return ResourceManager.GetString("PropertyLockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock End Date.
        /// </summary>
        public static string PropertyLockoutEndDateUtc {
            get {
                return ResourceManager.GetString("PropertyLockoutEndDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PropertyPasswordHash {
            get {
                return ResourceManager.GetString("PropertyPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PropertyPhoneNumber {
            get {
                return ResourceManager.GetString("PropertyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Confirmed.
        /// </summary>
        public static string PropertyPhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("PropertyPhoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Stamp.
        /// </summary>
        public static string PropertySecurityStamp {
            get {
                return ResourceManager.GetString("PropertySecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Enabled.
        /// </summary>
        public static string PropertyTwoFactorEnabled {
            get {
                return ResourceManager.GetString("PropertyTwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string PropertyUserName {
            get {
                return ResourceManager.GetString("PropertyUserName", resourceCulture);
            }
        }
    }
}
