//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLOB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PatternResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatternResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyLOB.Resources.PatternResources", typeof(PatternResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy}.
        /// </summary>
        public static string DataFormat_Date {
            get {
                return ResourceManager.GetString("DataFormat_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yy}.
        /// </summary>
        public static string DataFormat_Date2 {
            get {
                return ResourceManager.GetString("DataFormat_Date2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy HH:mm:ss.fff}.
        /// </summary>
        public static string DataFormat_DateTime {
            get {
                return ResourceManager.GetString("DataFormat_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yy HH:mm:ss.fff}.
        /// </summary>
        public static string DataFormat_DateTime2 {
            get {
                return ResourceManager.GetString("DataFormat_DateTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#####0.00}.
        /// </summary>
        public static string DataFormat_Float {
            get {
                return ResourceManager.GetString("DataFormat_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#####0}.
        /// </summary>
        public static string DataFormat_Integer {
            get {
                return ResourceManager.GetString("DataFormat_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:}.
        /// </summary>
        public static string DataFormat_String {
            get {
                return ResourceManager.GetString("DataFormat_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:HH:mm:ss.fff}.
        /// </summary>
        public static string DataFormat_Time {
            get {
                return ResourceManager.GetString("DataFormat_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        public static string Format_Date {
            get {
                return ResourceManager.GetString("Format_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy HH:mm:ss.
        /// </summary>
        public static string Format_DateTime {
            get {
                return ResourceManager.GetString("Format_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####0.00.
        /// </summary>
        public static string Format_Float {
            get {
                return ResourceManager.GetString("Format_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####0.
        /// </summary>
        public static string Format_Integer {
            get {
                return ResourceManager.GetString("Format_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Format_String {
            get {
                return ResourceManager.GetString("Format_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm:ss.
        /// </summary>
        public static string Format_Time {
            get {
                return ResourceManager.GetString("Format_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy}.
        /// </summary>
        public static string GridFormat_Date {
            get {
                return ResourceManager.GetString("GridFormat_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy HH:mm:ss}.
        /// </summary>
        public static string GridFormat_DateTime {
            get {
                return ResourceManager.GetString("GridFormat_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n2}.
        /// </summary>
        public static string GridFormat_Float {
            get {
                return ResourceManager.GetString("GridFormat_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:d}.
        /// </summary>
        public static string GridFormat_Integer {
            get {
                return ResourceManager.GetString("GridFormat_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:HH:mm:ss}.
        /// </summary>
        public static string GridFormat_Time {
            get {
                return ResourceManager.GetString("GridFormat_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[-+]$.
        /// </summary>
        public static string RegularExpression_Boolean {
            get {
                return ResourceManager.GetString("RegularExpression_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](18|19|20|)[0-9][0-9])$.
        /// </summary>
        public static string RegularExpression_Date {
            get {
                return ResourceManager.GetString("RegularExpression_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](18|19|20|)[0-9][0-9]\s(0[0-9]|1[0-9]|2[0-4]):([0-5][0-9]):([0-5][0-9]))$.
        /// </summary>
        public static string RegularExpression_DateTime {
            get {
                return ResourceManager.GetString("RegularExpression_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([\w\-]+\.)*[\w\- ]+@([\w\- ]+\.)+([\w\-]{2,3})$.
        /// </summary>
        public static string RegularExpression_Email {
            get {
                return ResourceManager.GetString("RegularExpression_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[-+]?[0-9]*\,?[0-9]*$.
        /// </summary>
        public static string RegularExpression_Float {
            get {
                return ResourceManager.GetString("RegularExpression_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[-+]?[0-9]*$.
        /// </summary>
        public static string RegularExpression_Integer {
            get {
                return ResourceManager.GetString("RegularExpression_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b$.
        /// </summary>
        public static string RegularExpression_IP {
            get {
                return ResourceManager.GetString("RegularExpression_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([\&apos;\.\^\~\´\`\\áÁ\\àÀ\\ãÃ\\âÂ\\éÉ\\èÈ\\êÊ\\íÍ\\ìÌ\\óÓ\\òÒ\\õÕ\\ôÔ\\úÚ\\ùÙ\\çÇaA-zZ]+)+((\s[\&apos;\.\^\~\´\`\\áÁ\\àÀ\\ãÃ\\âÂ\\éÉ\\èÈ\\êÊ\\íÍ\\ìÌ\\óÓ\\òÒ\\õÕ\\ôÔ\\úÚ\\ùÙ\\çÇaA-zZ]+)+)?$.
        /// </summary>
        public static string RegularExpression_Nome {
            get {
                return ResourceManager.GetString("RegularExpression_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{5}\-?\d{3}$.
        /// </summary>
        public static string RegularExpression_ptBR_CEP {
            get {
                return ResourceManager.GetString("RegularExpression_ptBR_CEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{2}.?\d{3}.?\d{3}/?\d{3}-?\d{2}$.
        /// </summary>
        public static string RegularExpression_ptBR_CNPJ {
            get {
                return ResourceManager.GetString("RegularExpression_ptBR_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{3}\.?\d{3}\.?\d{3}\-?\d{2}$.
        /// </summary>
        public static string RegularExpression_ptBR_CPF {
            get {
                return ResourceManager.GetString("RegularExpression_ptBR_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{2}$.
        /// </summary>
        public static string RegularExpression_ptBR_DDD {
            get {
                return ResourceManager.GetString("RegularExpression_ptBR_DDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\d{2})\d{4}-\d{4}$.
        /// </summary>
        public static string RegularExpression_ptBR_DDDTelefone {
            get {
                return ResourceManager.GetString("RegularExpression_ptBR_DDDTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{4}-\d{4}$.
        /// </summary>
        public static string RegularExpression_ptBR_Telefone {
            get {
                return ResourceManager.GetString("RegularExpression_ptBR_Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .*.
        /// </summary>
        public static string RegularExpression_String {
            get {
                return ResourceManager.GetString("RegularExpression_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((0[0-9]|1[0-9]|2[0-4]):([0-5][0-9]):([0-5][0-9]))$.
        /// </summary>
        public static string RegularExpression_Time {
            get {
                return ResourceManager.GetString("RegularExpression_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((http)|(https)|(ftp)):\/\/([\- \w]+\.)+\w{2,3}(\/ [%\-\w]+(\.\w{2,})?)*$.
        /// </summary>
        public static string RegularExpression_URL {
            get {
                return ResourceManager.GetString("RegularExpression_URL", resourceCulture);
            }
        }
    }
}
