//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLOB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SyncfusionPatternResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncfusionPatternResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyLOB.Resources.SyncfusionPatternResources", typeof(SyncfusionPatternResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy}.
        /// </summary>
        public static string GridFormat_Date {
            get {
                return ResourceManager.GetString("GridFormat_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yy}.
        /// </summary>
        public static string GridFormat_Date2 {
            get {
                return ResourceManager.GetString("GridFormat_Date2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy HH:mm:ss}.
        /// </summary>
        public static string GridFormat_DateTime {
            get {
                return ResourceManager.GetString("GridFormat_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yy HH:mm:ss}.
        /// </summary>
        public static string GridFormat_DateTime2 {
            get {
                return ResourceManager.GetString("GridFormat_DateTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n2}.
        /// </summary>
        public static string GridFormat_Float {
            get {
                return ResourceManager.GetString("GridFormat_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0}.
        /// </summary>
        public static string GridFormat_Integer {
            get {
                return ResourceManager.GetString("GridFormat_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:}.
        /// </summary>
        public static string GridFormat_String {
            get {
                return ResourceManager.GetString("GridFormat_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:HH:mm:ss}.
        /// </summary>
        public static string GridFormat_Time {
            get {
                return ResourceManager.GetString("GridFormat_Time", resourceCulture);
            }
        }
    }
}
